kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 3 control plane node and 1 workers
nodes:
- role: control-plane
# - role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."harbor-cjs.duckdns.org"]
    endpoint = ["https://kind:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."harbor-cjs.duckdns.org".tls]
    insecure_skip_verify = true
