apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
  namespace: jenkins-admin
spec:
  containers:
  - image: harbor-cjs.duckdns.org/edu/spring-test
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
  - name: registry-secret
status: {}
