apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-express
  namespace: ${USER_IDENTITY}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-express
  template:
    metadata:
      labels:
        app: hello-express
    spec:
      containers:
      - image: nexus-repo.nexus.cloud.35.209.207.26.nip.io/${USER_IDENTITY}/express-jenkins:1.0.0
        name: hello-express
        ports:
        - containerPort: 3000
